### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Combinatrix** [kpbs5/ros2.fish#2]
Error while installing.

<pre>~/.config/fish/conf.d/ros2.fish (line 30): &apos;return&apos; outside of function definition
not status is-interactive; and return
                               ^
from sourcing file ~/.config/fish/conf.d/ros2.fish
	called on line 189 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install kpbs5/ros2.fish&apos;
source: Error while reading file “~/.config/fish/conf.d/ros2.fish”
Installed 1 plugin/s
</pre>

**Comment by kpbaks** [comment]
What `fish --version` are you on?

**Comment by Combinatrix** [comment]
Hey

Was on 3.3.1 because this was the default.
Had to manually add the Repo and now i am on v3.7.0

Install now works without problems.

Thanks for the help
