### ISSUE TITLE
 Completion Error

### ISSUE THREAD

**Issue by Combinatrix** [kpbs5/ros2.fish#3]
Hello
Thanks for sharing your work!

Completion works until "ros2 command packet" (e.g. ros2 launch joy)
The next TAB throws this error:

<pre><font color="#005FD7">ros2</font> <font color="#00AFFF">launch</font> <font color="#00AFFF">joy</font> Command &apos;path&apos; not found, did you mean:
  command &apos;mpath&apos; from deb libmodule-path-perl (0.19-1.1)
  command &apos;patch&apos; from deb patch (2.7.6-7build2)
  command &apos;xpath&apos; from deb libxml-xpath-perl (1.44-1)
  command &apos;pat&apos; from deb dist (1:3.5-236-1)
  command &apos;path6&apos; from deb ipv6toolkit (2.0+ds.1-1)
Try: sudo apt install &lt;deb name&gt;
~/.config/fish/completions/ros2.fish (line 1): 
path basename $file
^
in command substitution
	called on line 114 of file ~/.config/fish/completions/ros2.fish
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
~/.config/fish/completions/ros2.fish (line 114): Unknown command
            printf &apos;%s\t%s\n&apos; (path basename $file) $pkg
                              ^
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
Command &apos;path&apos; not found, did you mean:
  command &apos;xpath&apos; from deb libxml-xpath-perl (1.44-1)
  command &apos;mpath&apos; from deb libmodule-path-perl (0.19-1.1)
  command &apos;pat&apos; from deb dist (1:3.5-236-1)
  command &apos;path6&apos; from deb ipv6toolkit (2.0+ds.1-1)
  command &apos;patch&apos; from deb patch (2.7.6-7build2)
Try: sudo apt install &lt;deb name&gt;
~/.config/fish/completions/ros2.fish (line 1): 
path basename $file
^
in command substitution
	called on line 114 of file ~/.config/fish/completions/ros2.fish
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
~/.config/fish/completions/ros2.fish (line 114): Unknown command
            printf &apos;%s\t%s\n&apos; (path basename $file) $pkg
                              ^
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
Command &apos;path&apos; not found, did you mean:
  command &apos;xpath&apos; from deb libxml-xpath-perl (1.44-1)
  command &apos;pat&apos; from deb dist (1:3.5-236-1)
  command &apos;mpath&apos; from deb libmodule-path-perl (0.19-1.1)
  command &apos;patch&apos; from deb patch (2.7.6-7build2)
  command &apos;path6&apos; from deb ipv6toolkit (2.0+ds.1-1)
Try: sudo apt install &lt;deb name&gt;
~/.config/fish/completions/ros2.fish (line 1): 
path basename $file
^
in command substitution
	called on line 114 of file ~/.config/fish/completions/ros2.fish
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
~/.config/fish/completions/ros2.fish (line 114): Unknown command
            printf &apos;%s\t%s\n&apos; (path basename $file) $pkg
                              ^
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
Command &apos;path&apos; not found, did you mean:
  command &apos;path6&apos; from deb ipv6toolkit (2.0+ds.1-1)
  command &apos;pat&apos; from deb dist (1:3.5-236-1)
  command &apos;patch&apos; from deb patch (2.7.6-7build2)
  command &apos;xpath&apos; from deb libxml-xpath-perl (1.44-1)
  command &apos;mpath&apos; from deb libmodule-path-perl (0.19-1.1)
Try: sudo apt install &lt;deb name&gt;
~/.config/fish/completions/ros2.fish (line 1): 
path basename $file
^
in command substitution
	called on line 114 of file ~/.config/fish/completions/ros2.fish
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
~/.config/fish/completions/ros2.fish (line 114): Unknown command
            printf &apos;%s\t%s\n&apos; (path basename $file) $pkg
                              ^
in function &apos;__fish_ros2_print_launch_files_in_package&apos; with arguments &apos;joy&apos;
in command substitution
</pre>

**Comment by kpbaks** [comment]
`path` is a `builtin` introduced in [fish v3.5.0](https://github.com/fish-shell/fish-shell/releases/tag/3.5.0). I can fix the issue by adding a check everywhere it is used, and if it is not available, then use the `dirname` binary from `coreutils`. While looking at the issue, I found that the repository also make use of the expanded functionality for abbreviations introduced in [fish v3.6.0](https://github.com/fish-shell/fish-shell/releases/tag/3.6.0). So I would rather just state in the README that the minimum required version for fish is ^3.6.0.

**Comment by Combinatrix** [comment]
Hey 

Thanks for the help. Now everything works as expected.
Default Versions on Ubuntu 22.04 LTS are outdated.
